apiVersion: v1
kind: ConfigMap
metadata:
  name: geneweaver-ui-nginx-conf
data:
  default.conf: |
    server {
      listen 80;

      root /srv/dist;
      index index.html;

      location /next {
        alias /srv/dist;
        try_files $uri $uri/ /next/index.html;
      }

    }
