#!/bin/bash

## file: makefile
## desc: Master makefile for biclique, k-clique, and bootstrap programs.
#

all:
	+$(MAKE) -C bicliquer
	+$(MAKE) -C biclique_tool
	+$(MAKE) -C bk-partite
	+$(MAKE) -C bstrap
	+$(MAKE) -C CS_Mset

clean:
	+$(MAKE) -C bicliquer clean
	+$(MAKE) -C biclique_tool clean
	+$(MAKE) -C bk-partite clean
	+$(MAKE) -C bstrap clean
