[project]
name = "geneweaver-api"
version = "0.20.0a0"
description = "The Geneweaver API"
readme = "README.md"
requires-python = ">=3.9,<4.0"
license = { text = "Apache-2.0" }

authors = [
    { name = "Alexander Berger", email = "alexander.berger@jax.org" },
    { name = "Francisco Castellanos", email = "francisco.castellanos@jax.org" },
    { name = "Sejal Desai", email = "sejal.desai@jax.org" },
]

dependencies = [
    "geneweaver-core>=0.20.0a0",
    "fastapi[all]>=0.115.5",
    "uvicorn[standard]>=0.32.1",
    "geneweaver-db>=0.20.0a0",
    "psycopg-pool>=3.1.7",
    "requests>=2.32.3",
    "python-jose[cryptography]>=3.3.0",
    "psycopg-binary==3.1.18",
    "pydantic-settings>=2.3.4",
    "jax-apiutils>=0.2.0a0",
]

[project.urls]
Homepage = "https://thejacksonlaboratory.github.io/geneweaver-docs/"
Repository = "https://github.com/TheJacksonLaboratory/geneweaver-api"

[dependency-groups]
dev = [
    "pytest-asyncio>=0.21.0",
    "ruff==0.15.11",
]

[tool.uv.workspace]
members = [
    "packages/*",
]

[tool.uv.sources]
geneweaver-core   = { workspace = true }
geneweaver-db     = { workspace = true }
geneweaver-client = { workspace = true }

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "geneweaver.api"

# TODO: Remove this when batch API is hooked up and tested.
[tool.coverage.report]
omit = ["*/batch.py"]
