apiVersion: v1
kind: ConfigMap
metadata:
  name: geneweaver-legacy-tools-config
data:
  CELERY_TRANSPORT: "redis"
  CELERY_HOST: "redis-master"
  CELERY_PORT: "6379"
  CELERY_DB: "1"
  CELERY_RESULT_BACKEND_TRANSPORT: "redis"
  CELERY_RESULT_BACKEND_HOST: "redis-master"
  CELERY_RESULT_BACKEND_PORT: "6379"
  CELERY_RESULT_BACKEND_DB: "1"
