import { AbbaResult } from './abba-models';

/**
 * A real `POST /tools/abba` response from dev (2026-10-08): seed genes Drd2 and Drd1, every
 * species, tiers 1-3, homology included. Trimmed to 7 of the 50 gene sets (chosen to cover
 * each tier, species and attribution present) and the top 6 of the 50 genes; long
 * descriptions are shortened. Every value kept is as the API returned it.
 */
export const ABBA_FIXTURE: AbbaResult = {
  tool: 'abba',
  parameters: {
    include_homology: true,
    min_genes: null,
    min_genesets: null,
    tiers: [1, 2, 3],
    species_ids: null,
  },
  available_genes: 520904,
  available_genesets: 222413,
  input_species: [
    'Caenorhabditis elegans',
    'Canis familiaris',
    'Danio rerio',
    'Drosophila melanogaster',
    'Gallus gallus',
    'Homo sapiens',
    'Macaca mulatta',
    'Mus musculus',
    'Rattus norvegicus',
  ],
  seed_genes: [
    {
      ode_gene_id: 476,
      symbol: 'Drd2',
      species_id: 1,
      species: 'Mus musculus',
    },
    {
      ode_gene_id: 2108,
      symbol: 'Drd1',
      species_id: 1,
      species: 'Mus musculus',
    },
    {
      ode_gene_id: 95723,
      symbol: 'DRD1',
      species_id: 2,
      species: 'Homo sapiens',
    },
    {
      ode_gene_id: 104798,
      symbol: 'DRD2',
      species_id: 2,
      species: 'Homo sapiens',
    },
    {
      ode_gene_id: 125560,
      symbol: 'dop-3',
      species_id: 8,
      species: 'Caenorhabditis elegans',
    },
    {
      ode_gene_id: 156163,
      symbol: 'DRD1',
      species_id: 10,
      species: 'Gallus gallus',
    },
    {
      ode_gene_id: 158353,
      symbol: 'DRD2',
      species_id: 10,
      species: 'Gallus gallus',
    },
    {
      ode_gene_id: 172915,
      symbol: 'DD1CR',
      species_id: 10,
      species: 'Gallus gallus',
    },
    {
      ode_gene_id: 194730,
      symbol: 'DRD1',
      species_id: 11,
      species: 'Canis familiaris',
    },
    {
      ode_gene_id: 195804,
      symbol: 'DRD2',
      species_id: 11,
      species: 'Canis familiaris',
    },
    {
      ode_gene_id: 238578,
      symbol: 'DRD1',
      species_id: 6,
      species: 'Macaca mulatta',
    },
    {
      ode_gene_id: 247129,
      symbol: 'DRD2',
      species_id: 6,
      species: 'Macaca mulatta',
    },
    {
      ode_gene_id: 329947,
      symbol: 'drd2a',
      species_id: 4,
      species: 'Danio rerio',
    },
    {
      ode_gene_id: 336034,
      symbol: 'drd2b',
      species_id: 4,
      species: 'Danio rerio',
    },
    {
      ode_gene_id: 350804,
      symbol: 'drd1',
      species_id: 4,
      species: 'Danio rerio',
    },
    {
      ode_gene_id: 359279,
      symbol: 'drd6b',
      species_id: 4,
      species: 'Danio rerio',
    },
    {
      ode_gene_id: 425683,
      symbol: 'Drd1',
      species_id: 3,
      species: 'Rattus norvegicus',
    },
    {
      ode_gene_id: 425684,
      symbol: 'Drd2',
      species_id: 3,
      species: 'Rattus norvegicus',
    },
    {
      ode_gene_id: 491635,
      symbol: 'Dop1R1',
      species_id: 5,
      species: 'Drosophila melanogaster',
    },
  ],
  genesets: [
    {
      gs_id: 282317,
      name: 'KEGG Geneset - "Neuroactive ligand-receptor interaction" pathway genes',
      abbreviation: 'Neuroactive ligand-receptor interaction',
      description:
        'Kyoto Encyclopedia of Genes and Genomes (KEGG) Geneset. This geneset contains genes that participate in the "Neuroactive ligand-receptor interaction" pathway. This set was automatically constructed using the KEGG API and enumerating all...',
      matches: 4,
      tier: 1,
      species_id: 4,
      attribution: 'KEGG',
      gene_count: 358,
    },
    {
      gs_id: 282184,
      name: 'KEGG Geneset - "Gap junction" pathway genes',
      abbreviation: 'Gap junction',
      description:
        'Kyoto Encyclopedia of Genes and Genomes (KEGG) Geneset. This geneset contains genes that participate in the "Gap junction" pathway. This set was automatically constructed using the KEGG API and enumerating all zebrafish pathways.\ngene2ke...',
      matches: 3,
      tier: 1,
      species_id: 4,
      attribution: 'KEGG',
      gene_count: 122,
    },
    {
      gs_id: 259156,
      name: 'alpha-(4-fluorophenyl)-4-(5-fluoro-2-pyrimidinyl)-1-piperazine butanol interacting with Mus musculus associated genes (MeSH:C050408) in CTD',
      abbreviation: 'alpha-(4-fluorophenyl)-4-(5-fluoro-2... M.m.',
      description:
        "Genes associated with Mus musculus that interact with the MeSH term 'alpha-(4-fluorophenyl)-4-(5-fluoro-2-pyrimidinyl)-1-piperazine butanol' (C050408). Incorporates data from 8 publications curated by the Comparative Toxicogenomics Datab...",
      matches: 2,
      tier: 1,
      species_id: 1,
      attribution: 'CTD',
      gene_count: 2,
    },
    {
      gs_id: 265224,
      name: 'epolactaene interacting with Rattus norvegicus associated genes (MeSH:C095351) in CTD',
      abbreviation: 'epolactaene R.n.',
      description:
        "Genes associated with Rattus norvegicus that interact with the MeSH term 'epolactaene' (C095351). Incorporates data from 2 publications curated by the Comparative Toxicogenomics Database (CTD). ODE Gene scores represent number of support...",
      matches: 2,
      tier: 1,
      species_id: 3,
      attribution: 'CTD',
      gene_count: 2,
    },
    {
      gs_id: 169623,
      name: 'MP:0010167 decreased response to stress-induced hyperthermia',
      abbreviation: 'decreased response to stress-induced hyperthermia (MP)',
      description:
        '"reduction or absence of the expected increase in core body termperature in response to stress or anticipatory anxiety" Data derived from MGI_GenePheno.rpt and the MP OBO tree dated 2016-11-07',
      matches: 2,
      tier: 1,
      species_id: 1,
      attribution: 'MP',
      gene_count: 4,
    },
    {
      gs_id: 321618,
      name: 'GO:0021769 orbitofrontal cortex development',
      abbreviation: 'GO:0021769',
      description:
        'Gene Ontology (GO) gene set. This set contains genes that have been annotated to the GO term "orbitofrontal cortex development", which is defined as "The progression of the orbitofrontal cortex over time from its initial formation until...',
      matches: 2,
      tier: 1,
      species_id: 3,
      attribution: 'GO',
      gene_count: 4,
    },
    {
      gs_id: 241264,
      name: '[MeSH] Mazindol : D008454',
      abbreviation: 'Mazindol',
      description:
        'Tricyclic anorexigenic agent unrelated to and less toxic than AMPHETAMINE, but with some similar side effects. It inhibits uptake of catecholamines and blocks the binding of cocaine to the dopamine uptake transporter. \n Generated by gene...',
      matches: 2,
      tier: 2,
      species_id: 2,
      attribution: 'MESH',
      gene_count: 4,
    },
  ],
  genes: [
    {
      ode_gene_id: 95197,
      symbol: 'TNF',
      symbols: ['TNF', 'DIF', 'TNF-alpha', 'TNFA', 'TNFSF2', 'TNLG1F'],
      species_id: 2,
      species: 'Homo sapiens',
      occurrences: 1453,
      tier_counts: {
        '1': 2461,
        '2': 4501,
        '3': 11,
        '4': 58,
        '5': 460,
      },
      species_counts: {
        '1': 2857,
        '2': 7564,
        '3': 1267,
        '6': 48,
        '11': 9,
      },
    },
    {
      ode_gene_id: 73850,
      symbol: 'BDNF',
      symbols: ['BDNF', 'ANON2', 'BULN2'],
      species_id: 2,
      species: 'Homo sapiens',
      occurrences: 1385,
      tier_counts: {
        '1': 820,
        '2': 2199,
        '3': 6,
        '4': 26,
        '5': 507,
      },
      species_counts: {
        '1': 2216,
        '2': 3608,
        '3': 698,
        '4': 42,
        '6': 9,
        '10': 17,
      },
    },
    {
      ode_gene_id: 91027,
      symbol: 'APOE',
      symbols: ['APOE', 'AD2', 'APO-E', 'ApoE4', 'LDLCQ5', 'LPG'],
      species_id: 2,
      species: 'Homo sapiens',
      occurrences: 1377,
      tier_counts: {
        '1': 1277,
        '2': 3143,
        '3': 14,
        '4': 45,
        '5': 453,
      },
      species_counts: {
        '1': 2515,
        '2': 4991,
        '3': 468,
        '6': 2,
      },
    },
    {
      ode_gene_id: 95345,
      symbol: 'IL6',
      symbols: [
        'IL6',
        'BSF-2',
        'BSF2',
        'CDF',
        'HSF',
        'IFN-beta-2',
        'IFNB2',
        'IL-6',
      ],
      species_id: 2,
      species: 'Homo sapiens',
      occurrences: 1346,
      tier_counts: {
        '1': 1821,
        '2': 3726,
        '3': 16,
        '4': 60,
        '5': 465,
      },
      species_counts: {
        '1': 2040,
        '2': 6172,
        '3': 1082,
        '6': 36,
        '10': 29,
        '11': 3,
      },
    },
    {
      ode_gene_id: 68586,
      symbol: 'MAPK1',
      symbols: [
        'MAPK1',
        'ERK-2',
        'ERK2',
        'ERT1',
        'MAPK2',
        'NS13',
        'P42MAPK',
        'PRKM1',
        'PRKM2',
        'p41',
        'p41mapk',
        'p42-MAPK',
      ],
      species_id: 2,
      species: 'Homo sapiens',
      occurrences: 1317,
      tier_counts: {
        '1': 2009,
        '2': 3132,
        '3': 5,
        '4': 37,
        '5': 421,
      },
      species_counts: {
        '1': 2500,
        '2': 5744,
        '3': 1141,
        '4': 49,
        '5': 296,
        '6': 85,
        '8': 115,
        '10': 7,
        '11': 14,
      },
    },
    {
      ode_gene_id: 97153,
      symbol: 'AKT1',
      symbols: ['AKT1', 'AKT', 'PKB', 'PKB-ALPHA', 'PRKBA', 'RAC', 'RAC-ALPHA'],
      species_id: 2,
      species: 'Homo sapiens',
      occurrences: 1309,
      tier_counts: {
        '1': 2158,
        '2': 3034,
        '3': 9,
        '4': 30,
        '5': 341,
      },
      species_counts: {
        '1': 2508,
        '2': 5655,
        '3': 756,
        '6': 66,
        '8': 281,
        '10': 4,
        '11': 1,
      },
    },
  ],
  max_occurrences: 1453,
  species: {
    '1': 'Mus musculus',
    '2': 'Homo sapiens',
    '3': 'Rattus norvegicus',
    '4': 'Danio rerio',
    '5': 'Drosophila melanogaster',
    '6': 'Macaca mulatta',
    '8': 'Caenorhabditis elegans',
    '9': 'Saccharomyces cerevisiae',
    '10': 'Gallus gallus',
    '11': 'Canis familiaris',
  },
  tiers: {
    '1': 'Tier I - Public Resource',
    '2': 'Tier II - Pro-curated',
    '3': 'Tier III - Public Curated',
    '4': 'Tier IV - Provisional',
    '5': 'Tier V - Group/Private',
  },
};
