"""Input/output schemas for the Jaccard Similarity tool."""

from __future__ import annotations

from geneweaver.tools.framework.schema import ToolInput, ToolOutput
from pydantic import BaseModel, Field


class JaccardDistribution(BaseModel):
    """A null distribution of Jaccard values for a pair of set sizes.

    Sourced from ``extsrc.jaccard_distribution_results`` (or generated by the legacy
    ``distribution_generator`` binary). ``frequencies`` is a list of
    ``(jaccard_value, frequency)`` pairs. Keyed by the *sorted* set sizes
    (``set_size1 <= set_size2``) and the homology flag.
    """

    set_size1: int
    set_size2: int
    homology: bool
    frequencies: list[tuple[float, int]]


class GenesetPairCounts(BaseModel):
    """Pairwise gene counts for two gene sets (indices into ``geneset_ids``).

    Mirrors the legacy pairwise-deletion counts: ``only_i`` = genes only in i (the legacy
    ``10``), ``only_j`` = genes only in j (``01``), ``intersection`` = shared (``11``).
    """

    i: int
    j: int
    only_i: int
    only_j: int
    intersection: int


class JaccardSimilarityInput(ToolInput):
    """Input for the Jaccard Similarity tool.

    Pairwise counts and the null distributions are resolved by the caller (membership +
    DB / distribution generation) and passed in, keeping the tool pure.
    """

    geneset_ids: list[str]
    include_homology: bool = False
    p_value_threshold: float = 0.05
    pairs: list[GenesetPairCounts] = Field(default_factory=list)
    distributions: list[JaccardDistribution] = Field(default_factory=list)


class JaccardSimilarityResult(BaseModel):
    """Jaccard coefficient and empirical p-value for one gene-set pair."""

    i: int
    j: int
    jaccard: float
    p_value: float | None  # None when there is no intersection (not computed)
    intersection: int
    only_i: int
    only_j: int


class JaccardSimilarityOutput(ToolOutput):
    """Per-pair Jaccard similarity results."""

    geneset_ids: list[str]
    include_homology: bool
    p_value_threshold: float
    results: list[JaccardSimilarityResult]
