name: 'Lint Code Definition'
on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to set up'
        required: false
        default: '3.10'
        type: string
jobs:
  format-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Install dependencies with uv
        run: uv sync --only-group dev

      - name: Run Ruff Linter
        run: uv run --only-group dev ruff check src/ tests/

      - name: Run Ruff Formatter
        run: uv run --only-group dev ruff format --check src/ tests/
